# Generated by Django 4.0.2 on 2022-03-04 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordvideo',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
