# Generated by Django 4.0.2 on 2022-03-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_learningvideo_image_url'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='learningvideo',
            table='learning_word',
        ),
    ]
