<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-02-22 06:54

from django.db import migrations, models
=======
# Generated by Django 4.0.2 on 2022-02-24 13:15

import apps.video.models
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> ff81d3f7ceb1135becb55af6279acb12d4b128b7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('user', '0001_initial'),
>>>>>>> ff81d3f7ceb1135becb55af6279acb12d4b128b7
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('url', models.FileField(default='posts/default', upload_to='video/%y%m%d')),
=======
                ('video_url', models.FileField(default='posts/default', upload_to=apps.video.models.upload_to3)),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
>>>>>>> ff81d3f7ceb1135becb55af6279acb12d4b128b7
            ],
        ),
    ]
