labels = {
    "back": 0,
    "belly": 1,
    "bleeding": 2,
    "burn": 3,
    "chest": 4,
    "choke": 5,
    "colic": 6,
    "cut": 7,
    "dislocation": 8,
    "ear": 9,
    "faint": 10,
    "fever": 11,
    "fracture": 12,
    "hand": 13,
    "head": 14,
    "heart_attack": 15,
    "high_fever": 16,
    "inside_of_thigh": 17,
    "knee": 18,
    "left_eye": 19,
    "neck": 20,
    "nose": 21,
    "painkiller": 22,
    "right_eye": 23,
    "seizure": 24,
    "shortness_of_breath": 25,
    "shoulder": 26,
    "waist": 27,
    "whirl": 28,
    "wrist": 29,
}


actions = [
    "back",
    "belly",
    "bleeding",
    "burn",
    "chest",
    "choke",
    "colic",
    "cut",
    "dislocation",
    "ear",
    "faint",
    "fever",
    "fracture",
    "hand",
    "head",
    "heart_attack",
    "high_fever",
    "inside_of_thigh",
    "knee",
    "left_eye",
    "neck",
    "nose",
    "painkiller",
    "right_eye",
    "seizure",
    "shortness_of_breath",
    "shoulder",
    "waist",
    "whirl",
    "wrist",
]