# Generated by Django 4.0.2 on 2022-02-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('phone_num', models.CharField(blank=True, max_length=15)),
                ('video_phone_num', models.CharField(blank=True, max_length=15, null=True)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'sign_center',
            },
        ),
    ]
