# Generated by Django 4.0.2 on 2022-02-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Center',
        ),
    ]
