# Generated by Django 4.0.2 on 2022-03-05 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'quiz_collection',
            },
        ),
        migrations.CreateModel(
            name='QuizDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_column='description', default='', max_length=20)),
                ('collection_id', models.ForeignKey(db_column='collection_id', default='', on_delete=django.db.models.deletion.CASCADE, to='quiz.quizcollection')),
            ],
            options={
                'db_table': 'quiz_description',
            },
        ),
        migrations.CreateModel(
            name='QuizUserCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(db_column='score', default='')),
                ('collection_id', models.ForeignKey(db_column='collection_id', default='', on_delete=django.db.models.deletion.CASCADE, to='quiz.quizcollection')),
                ('user_id', models.ForeignKey(db_column='user_id', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_user_collection',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30)),
                ('answer_id', models.ForeignKey(db_column='answer_id', default='', on_delete=django.db.models.deletion.CASCADE, to='quiz.quizdescription')),
                ('collection_id', models.ForeignKey(db_column='collection_id', default='', on_delete=django.db.models.deletion.CASCADE, to='quiz.quizcollection')),
            ],
            options={
                'db_table': 'quiz_question',
            },
        ),
    ]
