# Generated by Django 4.0.2 on 2022-03-05 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='video_id',
            field=models.ForeignKey(db_column='video_id', default='', on_delete=django.db.models.deletion.CASCADE, to='video.learningvideo'),
        ),
    ]
