# Generated by Django 4.0.2 on 2022-03-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizquestion_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizdescription',
            name='korean_name',
            field=models.CharField(db_column='korean_name', default='', max_length=20),
        ),
    ]
