# Generated by Django 3.1 on 2022-03-01 05:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_created_at_remove_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 1, 5, 48, 45, 921264, tzinfo=utc), verbose_name='생성된 날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정된 날짜'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
